#include "arduino_secrets.h"
#include <DHT.h>
#include <DHT_U.h>
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/1e06165a-4fab-4b02-ac9c-eedf0617d836 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight light;
  CloudTemperatureSensor temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

#define UART_PORT 1
#define UART1_TX_PIN 17
#define UART1_RX_PIN 16

#define DHTPIN 15
#define DHTTYPE DHT11
DHT dht(DHTPIN, DHTTYPE);

unsigned long previousMillis = 0;  // Stores the last time data was sent
const long interval = 5000;        // Interval at which to send data (milliseconds)

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  Serial1.begin(115200, SERIAL_8N1, UART1_RX_PIN, UART1_TX_PIN);
  Serial.println("ESP32 UART1 Initialized");

  pinMode(2,OUTPUT);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  unsigned long currentMillis = millis();

  if (currentMillis - previousMillis >= interval) {
    previousMillis = currentMillis;
    sendDHT11Data(); 
  
  }
  if (Serial1.available()) {
    String data = "";
    while (Serial1.available()) {
      data += char(Serial1.read());
    }
    Serial.print("Received from STM32: ");
    Serial.println(data);
  }

}


/*
  Since Light is READ_WRITE variable, onLightChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightChange()  {
  if(light==1)
  {
      Serial1.write("1");
  }
  if(light == 0)
  {
      Serial1.write("0");
  }
  digitalWrite(2,light);
  // Add your code here to act upon Light change
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void sendDHT11Data(){
  temperature = dht.readTemperature();
  if(isnan(temperature)){
    Serial.println("failed to reat the DHT sensor");
    return;
  }
  Serial.print("Temprature:");
  Serial.print(temperature);
  Serial.print("C");
}

void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}
